name: Print New Folder Name

on:
  pull_request:
    paths:
      - '**/'  # Listen for changes in any directory

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FOLDER_NAME: ""
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract folder name
        run: |
          added="${{ steps.abc.outputs.added }}"
          folder=$(echo "$added" | awk -F/ '{print $2}' | sort -u)
          echo "FOLDER_NAME=$folder" >> $GITHUB_ENV
      - name: Print folder name
        run: |
          echo "Folder name: $FOLDER_NAME"
      - name: Checkout PR
        uses: actions/checkout@v2.1.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run command from t1 folder
        run: |
          cd adapters 
          cd $FOLDER_NAME
          # Run your command here
          npm install
          npm run compile
          cd ..
          npm install
          npm run start $FOLDER_NAME


      - name: Upload to S3
        uses: actions/aws/cli@v2
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
      - name: Upload to S3
        run: s3 cp outputData.csv s3://linea-files/public/ --acl public-read
