name: Print Pull Request Changes

on:
  pull_request:
    paths:
      - '**/'  # Listen for changes in any directory

jobs:
  print_pull_request_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: Stockopedia/action-get-changed-files@v1
        id: get_changed
        with:
          ignore: "**/*.js" # glob
          foldersOnly: true # to only include folders in the output
          format: json # either json, csv or newline
      - name: Echo
        run: echo ${{ steps.get_changed.outputs.changed }}
