name: Print Pull Request Changes

on:
  pull_request:
    paths:
      - '**/'  # Listen for changes in any directory

jobs:
  print_pull_request_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print Added Files
        run: |
          git fetch origin main:main
          git diff --name-only main...HEAD | grep '^+' | sed 's/^+//' | while read filename; do
            echo "Added: $filename"
          done
