name: Print New Folder Name

on:
  pull_request:
    paths:
      - '**/'  # Listen for changes in any directory

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract folder names
        run: |
          echo "Added:"
          echo "${{ steps.abc.outputs.added }}" | awk -F/ '{print $1}' | sort -u > folders.txt
      - name: Checkout PR
        uses: actions/checkout@v2.1.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run script from t1 folder
        run: |
          cd $(head -n 1 folders.txt)
          # Run your script here
          ls
