name: Print Pull Request Changes

on:
  pull_request:
    paths:
      - '**/'  # Listen for changes in any directory

jobs:
  print_pull_request_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: Stockopedia/action-get-changed-files@v1
        id: get_changed
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ignore: "**/+(.github)"
          foldersOnly: true 
          format: csv
      - name: Echo changed files
        run: echo ${{ steps.get_changed.outputs.changed }}
