name: Print New Folder Name

on:
  pull_request:
    paths:
      - '**/'  # Listen for changes in any directory

jobs:
  print_new_folder_name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print pull request payload
        run: cat $GITHUB_EVENT_PATH

      - name: Extract new folder names
        run: |
          changed_files=$(jq -r '.pull_request | .files[] | select(.status == "added" or .status == "modified") | .filename' $GITHUB_EVENT_PATH)

          for file in $changed_files; do
            if [[ $file == */* ]]; then
              dirname=$(dirname "$file")
              echo "New folder added: $dirname"
            fi
          done
