name: Test-PRs
on:
  pull_request:
    paths:
      - '**/' 
jobs:
  print_new_folder_name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract new folder names
        run: |
          changed_files=$(jq -r '.pull_request.changed_files' $GITHUB_EVENT_PATH)
          for file in $changed_files; do
            if [[ $file =~ ^(.+)/[^/]+$ ]]; then
              dirname=${BASH_REMATCH[1]}
              echo "New folder added: $dirname"
            fi
          done
  
