name: Print Pull Request Changes

on:
  pull_request:
    paths:
      - '**/'  # Listen for changes in any directory

jobs:
  print_pull_request_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print Pull Request Changes
        run: |
          echo "Added files:"
          jq -r '.pull_request.additions | .[]' $GITHUB_EVENT_PATH

          echo "Modified files:"
          jq -r '.pull_request.changed_files | .[]' $GITHUB_EVENT_PATH

          echo "Removed files:"
          jq -r '.pull_request.deletions | .[]' $GITHUB_EVENT_PATH
