name: Print Pull Request Changes

on:
  pull_request:
    paths:
      - '**/'  # Listen for changes in any directory

jobs:
  print_pull_request_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Print Added Files
        run: |
          git fetch origin $GITHUB_BASE_REF:$GITHUB_BASE_REF
          git diff --name-only $GITHUB_BASE_REF...HEAD | grep '^+' | sed 's/^+//' | while read filename; do
            echo "Added: $filename"
          done
