name: Print Pull Request Changes

on:
  pull_request:
    paths:
      - '**/'  # Listen for changes in any directory

jobs:
  print_pull_request_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print Pull Request Changes
        run: |
          pull_request_payload=$(cat $GITHUB_EVENT_PATH)

          echo "Added files:"
          echo $pull_request_payload | jq -r '.pull_request.files[] | select(.status == "added") | .filename'

          echo "Modified files:"
          echo $pull_request_payload | jq -r '.pull_request.files[] | select(.status == "modified") | .filename'

          echo "Removed files:"
          echo $pull_request_payload | jq -r '.pull_request.files[] | select(.status == "removed") | .filename'
