name: Test-PRs
on:
  pull_request:
    paths:
      - '**/' 
jobs:
  print_new_folder_name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get PR details
        id: pr
        run: |
          echo "ADDITIONS=$(jq -r '.pull_request.additions' $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
          echo "CHANGED_FILES=$(jq -r '.pull_request.changed_files' $GITHUB_EVENT_PATH)" >> $GITHUB_ENV

      - name: Extract new folder names
        run: |
          additions="${{ env.ADDITIONS }}"
          changed_files="${{ env.CHANGED_FILES }}"
          for file in $changed_files; do
            if [ $(echo $file | grep '/' | wc -l) -eq 1 ]; then
              dirname=$(dirname $file)
              if ! echo "$additions" | grep -q "^$dirname\$"; then
                echo "New folder added: $dirname"
              fi
            fi
          done
  
